task:
  name: Build
  macos_instance:
    image: sequoia-codeql
  build_script: MACOS_VERSION='15.0' MACHINE_CONFIG=VMAPPLE bash -x build.sh
  codeql_script: MACOS_VERSION='15.0' MACHINE_CONFIG=VMAPPLE bash -x codeql.sh
  binary_artifacts:
    path: xnu-codeql.zip
