name: XNU BUILD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"
      - Makefile
      - .cirrus.yml
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        macos-version: [ '13.5' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deps
        run: |
          # brew update
          brew install bash blacktop/tap/ipsw
          # sudo ipsw dl kdk --host --install
          sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: kmutil help # This is to check for what flags are available
        run: |
          sysctl -n kern.bootobjectspath || true
          sw_vers
          kmutil inspect

      # - name: Cache JSONDB
      #   id: cache-jsondb
      #   uses: actions/cache@v4
      #   with:
      #     path: .cache/${{ matrix.macos-version }}/compile_commands.json
      #     key: ${{ matrix.macos-version }}-jsondb

      # - name: Build XNU JSON compilation database
      #   if: steps.cache-jsondb.outputs.cache-hit != 'true'
      #   run: |
      #     MACOS_VERSION='${{ matrix.macos-version }}' MACHINE_CONFIG=VMAPPLE JSONDB=1 bash -x build.sh

      - name: Build XNU
        run: |
          MACOS_VERSION='${{ matrix.macos-version }}' MACHINE_CONFIG=NONE KC_FILTER='com.apple.driver.SEPHibernation|com.apple.iokit.IOACPIFamily' bash -x build.sh
          ls -lah fakeroot/System/Library/Kernels/

      - uses: actions/upload-artifact@v4
        with:
          name: xnu-build-${{ matrix.macos-version }}
          path: |
            fakeroot/System/Library/Kernels/
            # fakeroot/oss-xnu.macOS.${{ matrix.macos-version }}.kc.vmapple
